apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kustomer
  name: kustomer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kustomer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kustomer
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://kustomer.dashboard:18889
          image: kustomer.api
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
